### ISSUE TITLE
hi ryan

### ISSUE THREAD

**Issue by ungoldman** [aranasaurus/messages#1]
How's it going?

**Comment by aranasaurus** [comment]
Oh, you know, I can't complain too much. How are you Nate?

**Comment by ungoldman** [comment]
Not bad, not bad.

**Comment by aranasaurus** [comment]
I'd like to play some Towerfall again some day. You should invite me over, and we could have Capri Suns and play video games and ride skate boards and stuff.

**Comment by ungoldman** [comment]
That sounds like a fine plan. @mannylopez recently mentioned the need to get that Towerfall tournament we've been talking about on the books.

**Comment by mannylopez** [comment]
Towerfall tournament!

Would the evening of Tuesday May 5th or Thursday May 7th work best for people?

@aranasaurus @ngoldman @courtf @jyaganeh

**Comment by ungoldman** [comment]
should I make a TowerfallPDX org?

towerfallpdx
pdxtowerfall
pdx-towerfall
towerfall-pdx
portland-towerfall
towerfall-portland

**Comment by jyaganeh** [comment]
I like Towerfall. Also github orgs are pretty neat. pdx-towerfall++

@mannylopez, I should be free either of those nights.

**Comment by aranasaurus** [comment]
I would proudly wear a pdx-towerfall badge on my githubs

**Comment by aranasaurus** [comment]
@mannylopez 5/7 is the first day of CocoaConf... that could both be a good or a bad thing. Although I already have a carte-blanch "I'll be home late" for all of the days of CocoaConf, so maybe that's a good thing.

**Comment by aranasaurus** [comment]
also because of that we may be able to bring in some out of towners, if we're in to that.

**Comment by ungoldman** [comment]
@pdx-towerfall is real

**Comment by mannylopez** [comment]
Yes for out of towners! I'm leaning for Thursday 5/7

**Comment by ungoldman** [comment]
My friend @lechin is getting @wearefine into towerfall, they may form a team! there will be blood!!!

**Comment by ungoldman** [comment]
:+1:
